# 5864_MLinEDU Beginner TA Lecture 2: Variables, loops, scope and array
Teacher: Chun-Shu Wei  
Teaching Assistant: 劉昱劭,Min-Jiun Tsai   
This week, we'll introduce :
1. variables,
2. if...else statement
3. while loop
4. for loop
5. scope
6. array
in Python.

## Section 1: Python Variables[1][2]
### Q: What is Python variable?
A variable is a **named location** used to **store data in the memory**.   
It is helpful to think of variables as a container that holds data which can be changed later throughout programming.   
For example,

In [1]:
number = 10
print('Value 10 is stored in memory address {}'.format(hex(id(number))))

Value 10 is stored in memory address 0x7ffa65af9460


Here, we have created a named `number`.   
We have assigned value 10 to the variable.    
You can think variable as a bag to store books in it and those books can be replaced at any time.

In [2]:
number = 10
print(type(number))
number = 1.1
print(type(number))
number

<class 'int'>
<class 'float'>


1.1

Initially, the value of `number` was 10. Later it's changed to 1.1.
#### Note:
In Python, we don't assign values to the variables, whereas Python gives the reference of the object (value) to the variable.

### Assigning a value to a Variable in Python
As you can see from the above example, you can use the assignment operator `=` to assign a value to a variable.

In [3]:
MLinEDU_website = "https://github.com/dollars9256741/5864_MLinEDU"
print(MLinEDU_website)

https://github.com/dollars9256741/5864_MLinEDU


In the above program, we assigned a value `https://github.com/dollars9256741/5864_MLinEDU` to the variable `MLinEDU_website`.  
Then we print the value assigned to `MLinEDU_website` i.e. https://github.com/dollars9256741/5864_MLinEDU.
#### Note : 
Python is a type inferred language; it can automatically know `https://github.com/dollars9256741/5864_MLinEDU` is a string and declare `MLinEDU_website` as a string.
#### Example 1: Changing the value of a variable

In [4]:
MLinEDU_website = "https://github.com/dollars9256741/5864_MLinEDU"
print(MLinEDU_website)

# assigning a new variable to MLinEDU_website
MLinEDU_website = "https://github.com/dollars9256741/5864_MLinEDU/week3"

print(MLinEDU_website)

https://github.com/dollars9256741/5864_MLinEDU
https://github.com/dollars9256741/5864_MLinEDU/week3


In the above program, we have assigned `https://github.com/dollars9256741/5864_MLinEDU` to the `MLinEDU_website` variable initially. Then, it's value is changed to `https://github.com/dollars9256741/5864_MLinEDU\week3`.

#### Example 2: Assigning multiple values to multiple variables

In [5]:
a, b, c = 5, 3.2, "Hello"
print (a)
print (b)
print (c)

5
3.2
Hello


If we want to assign the same value to multiple variables at once, we can do this as:

In [6]:
x = y = z = "same"
print (x)
print (y)
print (z)

same
same
same


The second program assigns the same string to all the three variables `x`, `y` and `z`.

### Constants
A constant is a type of variable whose value cannot be changed.   
It is helpful to think of constants as containers that hold information which cannot be changed later.  
Non technically, you can think of constant as a bag to store some books and those books cannot be replaced once placed inside the bag.
#### Example 3: Declaring and assigning value to a constant

In [1]:
#import Ipynb_importer
import Constant

ModuleNotFoundError: No module named 'Constant'

In [3]:
import Ipynb_importer

In [4]:
import Constant

In [5]:
Constant.PI=3.14

In [6]:
Constant.PI=3.14159625

Exception: (<class 'Constant.Constant.ConstError'>, "Can't change const value!")

In [7]:
Constant.GRAVITY=9.8

In [8]:
Constant.MOLE=6.02*(10^23)

In [9]:
Constant.MOLE=15

Exception: (<class 'Constant.Constant.ConstError'>, "Can't change const value!")

In [10]:
# Overflow
Constant.MOLE

174.57999999999998

In the above program, we create a Constant.ipynb module file.   
Then, we assign the constant value to PI and GRAVITY.   
After that, we import the constant module into Lecture_2.ipynb file.   
Finally, we print the constant value.

#### Note: 
In reality, we don't use constants in Python. The globals or constants module is used throughout the Python programs.


### Rules and Naming convention for variables and constants
1. Create a name that makes sense. 
    Suppose, `vowel` makes more sense than `v`.
2. Use camelCase notation to declare a variable. It starts with lowercase letter. For example: `myName`, `myAge` and `myAddress`.[6]
3. Use capital letters where possible to declare a constant. For example: `PI`, `G`, `MASS` and `TEMP`.
4. Never use special symbols like !, @, #, $, %... ...
5. Don't start name with a digit.
6. Constants are put into Python modules and meant not be changed.
7. Constant and variable names should have combination of letters in lowercase (a to z) or uppercase (A to Z) or digits (0 to 9) or an underscore "_".   
    For example: `snake_case`, `MACRO_CASE`, `camelCase` and `CapWords`.

## Section 2: if...else statement[2]
### Python If ... Else
#### Python Conditions and If statements
Python supports the usual logical conditions from mathematics:

+ Equals: `a == b`
+ Not Equals: `a != b`
+ Less than: `a < b`
+ Less than or equal to: `a <= b`
+ Greater than: `a > b`
+ Greater than or equal to: `a >= b`  

These conditions can be used in several ways, most commonly in "if statements" and loops.  
An "if statement" is written by using the if keyword.
#### Example 4:

In [11]:
a = 1
b = 5
if b > a:
    print("b is greater than a")

b is greater than a


#### Indentation
Python relies on indentation (whitespace at the beginning of a line) to define scope in the code.   
Other programming languages often use curly-brackets for this purpose.

In [12]:
a = 1
b = 5
if b > a:
print("b is greater than a")

IndentationError: expected an indented block (<ipython-input-12-9d627531ee70>, line 4)

### Elif
The elif keyword is pythons way of saying "if the previous conditions were not true, then try this condition".
#### Example 5:

In [13]:
a = 33.001
b = 33.001
if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")

a and b are equal


### Else
The else keyword catches anything which isn't caught by the preceding conditions.
#### Example 6:

In [14]:
a = 200
b = 33
if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")
else:
    print("a is greater than b")

a is greater than b


You can also have an else without the `elif`.

In [15]:
a = 200
b = 33
if b > a:
    print("b is greater than a")
else:
    print("b is not greater than a")

b is not greater than a


### Short Hand If
If you have only one statement to execute, you can put it on the same line as the if statement.

In [17]:
if Constant.GRAVITY > Constant.PI: print("{} is greater than {}".format(Constant.GRAVITY,Constant.PI))

9.8 is greater than 3.14


### Short Hand If ... Else
If you have only one statement to execute, one for if, and one for else, you can put it all on the same line:

In [19]:
print("A") if Constant.GRAVITY < Constant.PI else print("B")

B


You can also have multiple else statements on the same line:

In [20]:
a = 330
b = 330
print("A") if a > b else print("=") if a == b else print("B")
"""if a>b : 
        print("A")
   else:
       if a==b:
           print("=")
       else:
           print("B")""" 

=


'if a>b : \n        print("A")\n   else:\n       if a==b:\n           print("=")\n       else:\n           print("B")'

### Nested If
You can have if statements inside if statements, this is called nested if statements.

In [21]:
x = 41
if x > 10:
    print("Above ten,")
    if x > 20:
        print("and also above 20!")
    else:
        print("but not above 20.")

Above ten,
and also above 20!


## Section 3: Loops in Python
### Python Loops
Python has two primitive loop commands:
+ `while` loops
+ `for` loops

### The while Loop
With the `while` loop we can execute a set of statements as long as a condition is true.
#### Example 7: Print i as long as i is less than 6

In [22]:
i = 1
while i < 6:
    print(i)
    i += 1

1
2
3
4
5


The `while` loop requires relevant variables to be ready, in this example we need to define an indexing variable, `i`, which we set to 1.
#### Note: 
Remember to increment i, or else **the loop will continue forever**.
### The break Statement
With the `break` statement we can stop the loop even if the `while` condition is true:
#### Example 8: Exit the loop when i is 3

In [23]:
i = 1
while i < 6:
    print(i)
    if i == 3:
        break
    i += 1

1
2
3


### The continue Statement
With the `continue` statement we can stop the current iteration, and continue with the next.
#### Example 9: Continue to the next iteration if i is 3

In [24]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)

1
2
4
5
6


### The else Statement
With the `else` statement we can run a block of code once when the condition no longer is true.
#### Example 10: Print a message once the condition is false.

In [25]:
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


### The for loop
A `for` loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string).

This is less like the `for` keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages.

With the `for` loop we can execute a set of statements, once for each item in a list, tuple, set etc.
#### Note:
Python: pass by reference  
C: pass by value
#### Example 11: Print each fruit in a fruit list
The `for` loop does not require an indexing variable to set beforehand.

In [26]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)

apple
banana
cherry


#### Example 12: Looping Through a String
Even strings are iterable objects, they contain a sequence of characters

In [27]:
for x in "banana":
    print(x)

b
a
n
a
n
a


### The break Statement
With the `break` statement we can stop the loop before it has looped through all the items.
#### Example 13: Exit the loop when x is "banana".

In [28]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    print(x)
    if x == "banana":
        break

apple
banana


#### Example 14: Compared with Example 13!
Exit the loop when x is "banana", but this time **the break comes before the print**.

In [29]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        break
    print(x)

apple


### The continue Statement
With the `continue` statement we can stop the current iteration of the loop, and continue with the next.

In [30]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
    if x == "banana":
        continue
    print(x)

apple
cherry


#### Note: You can use continue function to select AVG_PM2.5 data in HW1 :D

### The range() Function
To loop through a set of code a specified number of times, we can use the `range()` function,
The `range()` function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.

In [31]:
for x in range(6):
    print(x)

0
1
2
3
4
5


#### Note:
1. `range(6)` is not the values of 0 to 6, but the values 0 to 5.
2. The `range()` function defaults to 0 as a starting value, however it is possible to specify the starting value by adding a parameter: `range(1, 6)`, which means values from 1 to 6 (but not including 6)

In [32]:
for x in range(1,6):
    print(x)

1
2
3
4
5


You can also set the step for  `range() `.  
The `range()` function defaults to increment the sequence by 1, however it is possible to specify the increment value by adding a third parameter:   
e.g. `range(0, 6, 2)`

In [33]:
for x in range(0,6,2):
    print(x)

0
2
4


### Else in For Loop
The `else` keyword in a `for loop` specifies a block of code to be executed when the loop is finished.
#### Example 15: Print all numbers from 0 to 5, and print a message when the loop has ended

In [34]:
for x in range(6):
    print(x)
else:
    print("Finally finished!")

0
1
2
3
4
5
Finally finished!


### Nested Loops
A nested loop is a loop inside a loop.  
The "inner loop" will be executed one time for each iteration of the "outer loop":
#### Example 16: Print each adjective for every fruit.

In [35]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]
for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


## Section 4: Python Iterator(Skip!)
An iterator is an object that contains a countable number of values.  
An iterator is an object that can be iterated upon, meaning that you can traverse through all the values.
Technically, in Python, an iterator is an object which implements the iterator protocol, which consist of the methods `__iter__()` and `__next__()`.
### Iterator vs Iterable
1. Lists, 
2. tuples,
3. dictionaries, and
4. sets   
are all **iterable objects**. They are iterable containers which you can get an iterator from.  

All these objects have a iter() method which is used to get an iterator.

In [36]:
mytuple = ("apple", "banana", "cherry")
myit = iter(mytuple)
print(next(myit))
print(next(myit))
print(next(myit))

apple
banana
cherry


Even strings are iterable objects, and can return an iterator.

In [37]:
mystr = "banana"
myit = iter(mystr)

print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))
print(next(myit))

b
a
n
a
n
a


### Looping Through an Iterator
We can also use a for loop to iterate through an iterable object.

In [38]:
mytuple = ("apple", "banana", "cherry")
for x in mytuple:
    print(x)

apple
banana
cherry


Iterate the characters of a string:  
The `for` loop actually creates an iterator object and executes the `next()` method for each loop.

In [39]:
mystr = "banana"
for x in mystr:
    print(x)

b
a
n
a
n
a


### Create an Iterator
To create an object/class as an iterator you have to implement the methods `__iter__()` and `__next__()` to your object.  
The `__iter__()` allows you to do operations (initializing etc.), but must always return the iterator object itself.  
The `__next__()` method also allows you to do operations, and must return the next item in the sequence.
#### Example 17: Create an iterator that returns numbers, starting with 1, and each sequence will increase by one (returning 1,2,3,4,5 etc.).

In [40]:
class MyNumbers:
    def __iter__(self):
        self.a = 1
        return self
    def __next__(self):
        x = self.a
        self.a += 1
        return x

myclass = MyNumbers()
myiter = iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

1
2
3
4
5


### StopIteration
The example above would continue forever if you had enough  next()  statements, or if it was used in a for loop.  

To prevent the iteration to go on forever, we can use the  `StopIteration ` statement.

In the  `__next__() ` method, we can add a terminating condition to raise an error if the iteration is done a specified number of times.
#### Example 18: Stop after 20 iterations

In [41]:
class MyNumbers:
    def __iter__(self):
        self.a = 1
        return self
    def __next__(self):
        if self.a <= 20:
            x = self.a
            self.a += 1
            return x
        else:
            raise StopIteration

myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


## Section 5: Python Scope
**A variable is only available from inside the region it is created.**  
This is called **scope**.
### Local Scope
**A variable created inside a function** belongs to the local scope of that function, and can **only be used inside that function**.
#### Example 17: A variable created inside a function is available inside that function.

In [42]:
def myfunc():
    local_scope_ = 300
    print(local_scope_)

In [43]:
myfunc()

300


In [44]:
local_scope_

NameError: name 'local_scope_' is not defined

### Function Inside Function
As explained in the example above, the variable x is not available outside the function, but it is available for any function inside the function.
#### Example 18: The local variable can be accessed from a function within the function.

In [45]:
def myfunc():
    x = 300
    def myinnerfunc():
        print(x)
    myinnerfunc()

In [46]:
myfunc()

300


In [47]:
myinnerfunc()

NameError: name 'myinnerfunc' is not defined

### Global Scope
A variable created in the main body of the Python code is a global variable and belongs to the global scope.  
Global variables are available from within any scope, global and local.
#### Example 19:  A variable created outside of a function is global and can be used by anyone.

In [48]:
global_scope=500

In [49]:
def myfunc():
    print(global_scope)

In [50]:
myfunc()

500


In [51]:
global_scope

500

### Naming Variables
If you operate with the same variable name inside and outside of a function, Python will treat them as two separate variables, one available in the global scope (outside the function) and one available in the local scope (inside the function).
#### Example 20: The function will print the local `var_1`, and then the code will print the global. 

In [52]:
var_1 = 300

In [53]:
def myfunc():
    var_1 = 200
    print(var_1)

In [54]:
myfunc()

200


In [55]:
print(var_1)

300


### Global Keyword
If you need to create a global variable, but are stuck in the local scope, you can use the global keyword.  
**The global keyword makes the variable global.**
#### Example 21: To change the value of a global variable inside a function, refer to the variable by using the `global` keyword.

In [56]:
var_2 = 20.56742

In [57]:
def myfunc():
    global var_2
    var_2 = 689

In [58]:
myfunc()

In [59]:
print(var_2)

689


## Section 6: Python Array[1][4]
### Arrays
Arrays are used to store multiple values in one single variable.

In [60]:
import numpy as np

In [61]:
cars = ["Ford", "Volvo", "BMW"]

### Access the Elements of an Array

In [62]:
cars[0]

'Ford'

### The Length of an Array
Use the `len()` method to return the length of an array (the number of elements in an array).

In [63]:
len(cars)

3

### Looping Array Elements
You can use the `for in` loop to loop through all the elements of an array.

In [64]:
for i in cars:
    print(i)

Ford
Volvo
BMW


In [65]:
arrayA = np.arange(12)
arrayA

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
arrayA = np.arange(12).reshape(3, 4)
arrayA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Indice of np.array: Row

In [67]:
arrayA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
arrayA[0]

array([0, 1, 2, 3])

In [69]:
arrayA[0,:]

array([0, 1, 2, 3])

In [70]:
arrayA[-1]

array([ 8,  9, 10, 11])

In [71]:
arrayA[-2]

array([4, 5, 6, 7])

In [72]:
arrayA[-15]

IndexError: index -15 is out of bounds for axis 0 with size 3

### Indice of np.array: Column

In [73]:
arrayA

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
arrayA[:,1]

array([1, 5, 9])

In [75]:
arrayA[:,-1]

array([ 3,  7, 11])

In [76]:
arrayA[:,-2]

array([ 2,  6, 10])

In [77]:
arrayA[:,-3]

array([1, 5, 9])

In [78]:
arrayA[:,-4]

array([0, 4, 8])

### np.ones(row,column) and np.zeros(row,column) 

In [79]:
arrayB = np.ones((1, 4))
arrayB

array([[1., 1., 1., 1.]])

In [80]:
arrayC = np.zeros((2, 5))
arrayC

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
# Use np.shape(array) to check array size
np.shape(arrayB)

(1, 4)

### Add array element
Use `np.append(array, value, axis)`
#### Example 22: When `axis` is not given...

In [82]:
np.append(arrayA, arrayB)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  1.,
        1.,  1.,  1.])

In [83]:
np.append(arrayA, arrayC)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Example 23: Compared with Example 22
When  `axis` is given...

In [84]:
# if axis=0, add value along row direction 
np.append(arrayA, arrayB,axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  1.,  1.,  1.]])

In [85]:
print(np.shape(arrayA))
print(np.shape(arrayB))

(3, 4)
(1, 4)


In [86]:
# if we add value into array with inconsistent shape, we'll get ValueError 
np.append(arrayA, np.ones((1, 3)), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [87]:
# Shape of array: np.shape(arrayA) is (3,4)
np.append(arrayA, np.ones((1, 4)), axis=0)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [ 1.,  1.,  1.,  1.]])

In [88]:
# if axis=0, add value along column direction
np.append(arrayA, np.ones((3, 1)), axis=1)

array([[ 0.,  1.,  2.,  3.,  1.],
       [ 4.,  5.,  6.,  7.,  1.],
       [ 8.,  9., 10., 11.,  1.]])

### Removing Array Elements
You can use the `pop()` method to remove an element from the array.

In [89]:
cars.pop(1)
cars

['Ford', 'BMW']

You can also use the `remove()` method to remove an element from the array.

In [90]:
cars.remove("BMW")
cars

['Ford']

### Can we use np.array as a np.matrix? 

In [91]:
matrixA=np.matrix([[1,2,3],[4,5,6]])
matrixA

matrix([[1, 2, 3],
        [4, 5, 6]])

In [92]:
arrayA=np.array([[1,2,3],[4,5,6]])
arrayA

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
matrixB=np.matrix([1,1,1])
print(np.shape(matrixB))
matrixB.T

(1, 3)


matrix([[1],
        [1],
        [1]])

In [94]:
matrix_A_row_sum=matrixA*matrixB.T
matrix_A_row_sum

matrix([[ 6],
        [15]])

In [95]:
matrixC=np.matrix([1,1])
matrixC

matrix([[1, 1]])

In [96]:
matrix_A_column_sum=matrixC*matrixA
matrix_A_column_sum

matrix([[5, 7, 9]])

In [97]:
arrayA=np.array([[1,2,3],[4,5,6]])
arrayB=np.ones(3)
arrayC=np.ones(2)

In [98]:
arrayA_row_sum=arrayA.dot(arrayB.T)
arrayA_row_sum

array([ 6., 15.])

In [99]:
arrayA_column_sum=arrayC.dot(arrayA)
arrayA_column_sum

array([5., 7., 9.])

## Reference
1. https://www.w3schools.com/python/
2. https://www.programiz.com/python-programming/ 
3. https://www.tutorialsteacher.com/python/error-types-in-python
4. https://likegeeks.com/numpy-array-tutorial/
5. https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Importing%20Notebooks.html
6. https://zh.wikipedia.org/wiki/%E9%A7%9D%E5%B3%B0%E5%BC%8F%E5%A4%A7%E5%B0%8F%E5%AF%AB